<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            //accounting
            ['name' => 'accounting', 'display_name' => 'Accessing Accounting Menu', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.chart_of_accounts.index', 'display_name' => 'View Chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.chart_of_accounts.create', 'display_name' => 'Create Chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.chart_of_accounts.update', 'display_name' => 'Edit Chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.chart_of_accounts.destroy', 'display_name' => 'Delete Chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.financial_periods.index', 'display_name' => 'View Financial Periods', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.financial_periods.create', 'display_name' => 'Create Financial Periods', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.financial_periods.update', 'display_name' => 'Edit Financial Periods', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.financial_periods.destroy', 'display_name' => 'Delete Financial Periods', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.journal_entries.index', 'display_name' => 'View Journal Entries', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.journal_entries.create', 'display_name' => 'Create Journal Entries', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.journal_entries.update', 'display_name' => 'Edit Journal Entries', 'module' => 'Accounting', 'guard_name' => 'web'],
            ['name' => 'accounting.journal_entries.reverse', 'display_name' => 'Reverse Journal Entries', 'module' => 'Accounting', 'guard_name' => 'web'],
            //activity log
            ['name' => 'activity_logs', 'display_name' => 'Access Activity Logs Menu', 'module' => 'Activitylog', 'guard_name' => 'web'],
            ['name' => 'activity_logs.index', 'display_name' => 'View Activity Logs', 'module' => 'Activitylog', 'guard_name' => 'web'],
            ['name' => 'activity_logs.destroy', 'display_name' => 'Delete Activity Logs', 'module' => 'Activitylog', 'guard_name' => 'web'],
            //branches
            ['name' => 'branches', 'display_name' => 'Access Branches Menu', 'module' => 'Branch', 'guard_name' => 'web'],
            ['name' => 'branches.index', 'display_name' => 'View Branches', 'module' => 'Branch', 'guard_name' => 'web'],
            ['name' => 'branches.create', 'display_name' => 'Create Branches', 'module' => 'Branch', 'guard_name' => 'web'],
            ['name' => 'branches.update', 'display_name' => 'Edit Branches', 'module' => 'Branch', 'guard_name' => 'web'],
            ['name' => 'branches.destroy', 'display_name' => 'Delete Branches', 'module' => 'Branch', 'guard_name' => 'web'],
            ['name' => 'branches.assign_user', 'display_name' => 'Assign Users', 'module' => 'Branch', 'guard_name' => 'web'],
            //members
            ['name' => 'members', 'display_name' => 'Access Members Menu', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.index', 'display_name' => 'View Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.index_own', 'display_name' => 'View Own Members Only', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.create', 'display_name' => 'Create Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.update', 'display_name' => 'Edit Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.update_own', 'display_name' => 'Edit Own Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.activate', 'display_name' => 'Activate Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.activate_own', 'display_name' => 'Activate Own Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.destroy', 'display_name' => 'Delete Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.destroy_own', 'display_name' => 'Delete Own Members', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.users.index', 'display_name' => 'View Member Users', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.users.create', 'display_name' => 'Create Member Users', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.users.destroy', 'display_name' => 'Delete Member Users', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.titles.index', 'display_name' => 'View Titles', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.titles.create', 'display_name' => 'Create Titles', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.titles.update', 'display_name' => 'Edit Titles', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.titles.destroy', 'display_name' => 'Delete Titles', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.categories.index', 'display_name' => 'View Categories', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.categories.create', 'display_name' => 'Create Categories', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.categories.update', 'display_name' => 'Edit Categories', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.categories.destroy', 'display_name' => 'Delete Categories', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.designations.index', 'display_name' => 'View Designations', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.designations.create', 'display_name' => 'Create Designations', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.designations.update', 'display_name' => 'Edit Designations', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.designations.destroy', 'display_name' => 'Delete Designations', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.professions.index', 'display_name' => 'View Professions', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.professions.create', 'display_name' => 'Create Professions', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.professions.update', 'display_name' => 'Edit Professions', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.professions.destroy', 'display_name' => 'Delete Professions', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.member_relationships.index', 'display_name' => 'View Member Relationships', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.member_relationships.create', 'display_name' => 'Create Member Relationships', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.member_relationships.update', 'display_name' => 'Edit Member Relationships', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.member_relationships.destroy', 'display_name' => 'Delete Member Relationships', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.files.index', 'display_name' => 'View Files', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.files.create', 'display_name' => 'Create Files', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.files.update', 'display_name' => 'Edit Files', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.files.destroy', 'display_name' => 'Delete Files', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.beneficiaries.index', 'display_name' => 'View Beneficiaries', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.beneficiaries.create', 'display_name' => 'Create Beneficiaries', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.beneficiaries.update', 'display_name' => 'Edit Beneficiaries', 'module' => 'Member', 'guard_name' => 'web'],
            ['name' => 'members.beneficiaries.destroy', 'display_name' => 'Delete Beneficiaries', 'module' => 'Member', 'guard_name' => 'web'],
            //communication campaigns
            ['name' => 'communication', 'display_name' => 'Access Communication Menu', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.index', 'display_name' => 'View Communication', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.campaigns.index', 'display_name' => 'View Campaigns', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.campaigns.create', 'display_name' => 'Create Campaigns', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.campaigns.update', 'display_name' => 'Edit Campaigns', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.campaigns.destroy', 'display_name' => 'Delete Campaigns', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.logs.index', 'display_name' => 'View Logs', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.logs.create', 'display_name' => 'Create Logs', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.logs.update', 'display_name' => 'Edit Logs', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.logs.destroy', 'display_name' => 'Delete Logs', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.sms_gateways.index', 'display_name' => 'View SMS Gateways', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.sms_gateways.create', 'display_name' => 'Create SMS Gateways', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.sms_gateways.update', 'display_name' => 'Edit SMS Gateways', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.sms_gateways.destroy', 'display_name' => 'Delete SMS Gateways', 'module' => 'Communication', 'guard_name' => 'web'],
            ['name' => 'communication.templates.index', 'module' => 'Communication', 'display_name' => 'View Templates', 'guard_name' => 'web'],
            ['name' => 'communication.templates.create', 'module' => 'Communication', 'display_name' => 'Create Templates', 'guard_name' => 'web'],
            ['name' => 'communication.templates.update', 'module' => 'Communication', 'display_name' => 'Update Templates', 'guard_name' => 'web'],
            ['name' => 'communication.templates.destroy', 'module' => 'Communication', 'display_name' => 'Delete Templates', 'guard_name' => 'web'],
            //payment types
            ['name' => 'payment_types', 'display_name' => 'Access Payment Types Menu', 'module' => 'Payment Types', 'guard_name' => 'web'],
            ['name' => 'payment_types.index', 'display_name' => 'View Payment Types', 'module' => 'Payment Types', 'guard_name' => 'web'],
            ['name' => 'payment_types.create', 'display_name' => 'Create Payment Types', 'module' => 'Payment Types', 'guard_name' => 'web'],
            ['name' => 'payment_types.update', 'display_name' => 'Edit Payment Types', 'module' => 'Payment Types', 'guard_name' => 'web'],
            ['name' => 'payment_types.destroy', 'display_name' => 'Delete Payment Types', 'module' => 'Payment Types', 'guard_name' => 'web'],
            //files
            ['name' => 'files', 'display_name' => 'Access File Manager', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.index', 'display_name' => 'View File Manager', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.create', 'display_name' => 'Create Files', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.update', 'display_name' => 'Edit Files', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.destroy', 'display_name' => 'Delete Files', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.types.index', 'display_name' => 'View File Types', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.types.create', 'display_name' => 'Create File Types', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.types.update', 'display_name' => 'Edit File Types', 'module' => 'Files', 'guard_name' => 'web'],
            ['name' => 'files.types.destroy', 'display_name' => 'Delete File Types', 'module' => 'Files', 'guard_name' => 'web'],
            //currencies
            ['name' => 'currencies', 'display_name' => 'Access Currencies Menu', 'module' => 'Currency', 'guard_name' => 'web'],
            ['name' => 'currencies.index', 'display_name' => 'View Currencies', 'module' => 'Currency', 'guard_name' => 'web'],
            ['name' => 'currencies.create', 'display_name' => 'Create Currencies', 'module' => 'Currency', 'guard_name' => 'web'],
            ['name' => 'currencies.update', 'display_name' => 'Edit Currencies', 'module' => 'Currency', 'guard_name' => 'web'],
            ['name' => 'currencies.destroy', 'display_name' => 'Delete Currencies', 'module' => 'Currency', 'guard_name' => 'web'],
            //custom fields
            ['name' => 'custom_fields', 'display_name' => 'Access Custom Fields Menu', 'module' => 'CustomField', 'guard_name' => 'web'],
            ['name' => 'custom_fields.index', 'display_name' => 'View Custom Fields', 'module' => 'CustomField', 'guard_name' => 'web'],
            ['name' => 'custom_fields.create', 'display_name' => 'Create Custom Field', 'module' => 'CustomField', 'guard_name' => 'web'],
            ['name' => 'custom_fields.update', 'display_name' => 'Edit Custom Field', 'module' => 'CustomField', 'guard_name' => 'web'],
            ['name' => 'custom_fields.destroy', 'display_name' => 'Delete Custom Field', 'module' => 'CustomField', 'guard_name' => 'web'],

            //loans
            ['name' => 'loans', 'display_name' => 'Access Loans Menu', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.index', 'display_name' => 'View Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.create', 'display_name' => 'Create Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.update', 'display_name' => 'Edit Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.destroy', 'display_name' => 'Delete Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.approve_loan', 'display_name' => 'Approve/Reject Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.disburse_loan', 'display_name' => 'Disburse Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.withdraw_loan', 'display_name' => 'Withdraw Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.write_off_loan', 'display_name' => 'Write Off Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.reschedule_loan', 'display_name' => 'Reschedule Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.close_loan', 'display_name' => 'Close Loans', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.calculator', 'display_name' => 'Use Loan Calculator', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.loan_history', 'display_name' => 'View Loan History', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.products.index', 'display_name' => 'View Loan Products', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.products.create', 'display_name' => 'Create Loan Products', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.products.update', 'display_name' => 'Edit Loan Products', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.products.destroy', 'display_name' => 'Delete Loan Products', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.schedules.index', 'display_name' => 'View Repayment Schedules', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.schedules.email', 'display_name' => 'Create Repayment Schedules', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.schedules.update', 'display_name' => 'Edit Repayment Schedules', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.transactions.index', 'display_name' => 'View Transactions', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.transactions.create', 'display_name' => 'Create Transactions', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.transactions.update', 'display_name' => 'Edit Transactions', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.transactions.destroy', 'display_name' => 'Delete/Reverse Transactions', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.charges.index', 'display_name' => 'View Charges', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.charges.create', 'display_name' => 'Create Charges', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.charges.update', 'display_name' => 'Edit Charges', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.charges.destroy', 'display_name' => 'Delete Charges', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.index', 'display_name' => 'View Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.disburse', 'display_name' => 'Disburse Approved Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.approve', 'display_name' => 'Approve Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.update_checklist_items', 'display_name' => 'Update Loan Application Checklist Items', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.view_checklist_items', 'display_name' => 'View Loan Application Checklist Items', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.create', 'display_name' => 'Create Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.update', 'display_name' => 'Edit Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.destroy', 'display_name' => 'Delete Loan Applications', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.approval_stages.index', 'display_name' => 'View Loan Application Approval Stages', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.approval_stages.change_status_for_all', 'display_name' => 'Change Loan Application Approval Stage Statuses', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.applications.approval_stages.assign', 'display_name' => 'Assign Application Approval Stage', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.credit_checks.index', 'display_name' => 'View Credit Checks', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.credit_checks.create', 'display_name' => 'Create Credit Checks', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.credit_checks.update', 'display_name' => 'Edit Credit Checks', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.credit_checks.destroy', 'display_name' => 'Delete Credit Checks', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.loan_provisioning.index', 'display_name' => 'View Loan Provisioning', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.loan_provisioning.create', 'display_name' => 'Create Loan Provisioning', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.loan_provisioning.update', 'display_name' => 'Edit Loan Provisioning', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.loan_provisioning.destroy', 'display_name' => 'Delete Loan Provisioning', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.purposes.index', 'display_name' => 'View Purposes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.purposes.create', 'display_name' => 'Create Purposes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.purposes.update', 'display_name' => 'Edit Purposes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.purposes.destroy', 'display_name' => 'Delete Purposes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.files.index', 'display_name' => 'View Files', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.files.create', 'display_name' => 'Create Files', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.files.update', 'display_name' => 'Edit Files', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.files.destroy', 'display_name' => 'Delete Files', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.notes.index', 'display_name' => 'View Notes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.notes.create', 'display_name' => 'Create Notes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.notes.update', 'display_name' => 'Edit Notes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.notes.destroy', 'display_name' => 'Delete Notes', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.histories.index', 'display_name' => 'View History', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.checklists.index', 'display_name' => 'View Checklists', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.checklists.create', 'display_name' => 'Create Checklists', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.checklists.update', 'display_name' => 'Edit Checklists', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.checklists.destroy', 'display_name' => 'Delete Checklists', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.approval_stages.index', 'display_name' => 'View Approval Stages', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.approval_stages.create', 'display_name' => 'Create Approval Stages', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.approval_stages.update', 'display_name' => 'Edit Approval Stages', 'module' => 'Loan', 'guard_name' => 'web'],
            ['name' => 'loans.approval_stages.destroy', 'display_name' => 'Delete Approval Stages', 'module' => 'Loan', 'guard_name' => 'web'],

            //reports
            ['name' => 'reports', 'display_name' => 'Access Reports', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.index', 'display_name' => 'View Reports', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.index', 'display_name' => 'View Loan Reports', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.collection_sheet', 'display_name' => 'View Loan Collection Sheet Report', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.repayments', 'display_name' => 'View Loan Repayments Report', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.expected_repayments', 'display_name' => 'View Expected Loan Repayments Reports', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.arrears', 'display_name' => 'View Loan Arrears Reports', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.disbursement', 'display_name' => 'View Loan Disbursement Report', 'module' => 'Report', 'guard_name' => 'web'],
            ['name' => 'reports.loans.portfolio_at_risk', 'display_name' => 'View Loan Portfolio At Risk Report', 'module' => 'Report', 'guard_name' => 'web'],

            //users
            ['name' => 'users', 'display_name' => 'Access Users Menu', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.index', 'display_name' => 'View Users', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.create', 'display_name' => 'Create Users', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.update', 'display_name' => 'Edit Users', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.destroy', 'display_name' => 'Delete Users', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.roles.index', 'display_name' => 'View Roles', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.roles.create', 'display_name' => 'Create Roles', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.roles.update', 'display_name' => 'Edit Roles', 'module' => 'User', 'guard_name' => 'web'],
            ['name' => 'users.roles.destroy', 'display_name' => 'Delete Roles', 'module' => 'User', 'guard_name' => 'web'],
            //settings
            ['name' => 'settings', 'display_name' => 'Access settings menu', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.index', 'display_name' => 'View settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.organisation', 'display_name' => 'View Organisation Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.general', 'display_name' => 'View General Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.system', 'display_name' => 'View System Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.sms', 'display_name' => 'View SMS Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.email', 'display_name' => 'View Email Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.other', 'display_name' => 'View Other Settings', 'module' => 'Setting', 'guard_name' => 'web'],
            ['name' => 'settings.update', 'display_name' => 'Edit Settings', 'module' => 'Setting', 'guard_name' => 'web'],
        ]);
    }
}
