<?php
return [
    [
        'id' => 'TotalPatientsCount',
        'permission' => '',
        'x' => 0,
        'y' => 0,
        'w' => 2,
        'h' => 2,
        'name' => 'Total Patients Count',
        'description' => 'View Total Patients Count',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [
        'id' => 'TotalConsultationsCount',
        'permission' => '',
        'x' => 2,
        'y' => 0,
        'w' => 2,
        'h' => 2,
        'name' => 'Total Consultations Count',
        'description' => 'View Total Consultations Count',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [
        'id' => 'TotalAppointmentsCount',
        'permission' => '',
        'x' => 4,
        'y' => 0,
        'w' => 2,
        'h' => 2,
        'name' => 'Total Appointments Count',
        'description' => 'View Total Appointments Count',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [
        'id' => 'TotalPaymentsAmount',
        'permission' => '',
        'x' => 6,
        'y' => 0,
        'w' => 2,
        'h' => 2,
        'name' => 'Total Payments Amount',
        'description' => 'View Total Payments Amount',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [
        'id' => 'WaitingList',
        'permission' => '',
        'x' => 0,
        'y' => 4,
        'w' => 4,
        'h' => 4,
        'name' => 'Waiting List',
        'description' => 'View Waiting List',
        'refresh' => true,
        'refresh_rate' => 1000,
    ],
    [
        'id' => 'AppointmentsCalendar',
        'permission' => '',
        'x' => 4,
        'y' => 4,
        'w' => 4,
        'h' => 4,
        'name' => 'Appointments Calendar',
        'description' => 'View Appointments Calendar',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [
        'id' => 'AppointmentsByStatusPieChart',
        'permission' => '',
        'x' => 0,
        'y' => 8,
        'w' => 4,
        'h' => 4,
        'name' => 'Appointments By Status Pie Chart',
        'description' => 'View Appointments By Status Pie Chart',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'AppointmentsByPeriodGraph',
        'permission' => '',
        'x' => 4,
        'y' => 8,
        'w' => 4,
        'h' => 4,
        'name' => 'Appointments By Period Graph',
        'description' => 'View Appointments By Period Graph',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'PaymentsByPaymentTypePieChart',
        'permission' => '',
        'x' => 4,
        'y' => 8,
        'w' => 4,
        'h' => 4,
        'name' => 'Payments By Payment Type Pie Chart',
        'description' => 'View Payments By Payment Type Pie Chart',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'PaymentsByPeriodGraph',
        'permission' => '',
        'x' => 0,
        'y' => 12,
        'w' => 4,
        'h' => 4,
        'name' => 'Payments By Period Graph',
        'description' => 'View Payments By Period Graph',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'IncomeVsExpensesPieChart',
        'permission' => '',
        'x' => 4,
        'y' => 12,
        'w' => 4,
        'h' => 4,
        'name' => 'Income vs Expenses Pie Chart',
        'description' => 'View Income vs Expenses Pie Chart',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'IncomeVsExpensesByPeriod',
        'permission' => '',
        'x' => 8,
        'y' => 12,
        'w' => 4,
        'h' => 4,
        'name' => 'Income vs Expenses By Period',
        'description' => 'View Income vs Expenses By Period',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
    [

        'id' => 'ConsultationsByPeriodGraph',
        'permission' => '',
        'x' => 0,
        'y' => 16,
        'w' => 4,
        'h' => 4,
        'name' => 'Consultations By Period Graph',
        'description' => 'View Consultations By Period',
        'refresh' => false,
        'refresh_rate' => 300,
    ],
];
